name: coleen
description: Simple all-in-one Flutter demo using Provider
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  

